name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
        - '**.md'

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vocard:latest
      
    - name: Log in to GitHub Docker Registry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push the Docker image
      run: |
        docker tag vocard:latest ghcr.io/chocomeow/vocard:latest  # Ensure lowercase
        docker push ghcr.io/chocomeow/vocard:latest  # Ensure lowercase